using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;
using NUnit.Framework;
using UnityEngine;

namespace WanderingCity.Tests
{
    public sealed class RulesTests
    {
        GameState s; string folder, path;
        [SetUp] public void SetUp() { s = new GameState(); folder = Path.Combine(Path.GetTempPath(), "wandering-tests-" + Guid.NewGuid().ToString("N")); Directory.CreateDirectory(folder); path = Path.Combine(folder, "save.json"); }
        [TearDown] public void TearDown() { Directory.Delete(folder, true); }
        void Add(string id, int count) => Assert.IsTrue(Rules.Transact(s, new Dictionary<string, int> { [id] = count }));
        string Snapshot() => JsonUtility.ToJson(s);
        [Test] public void StacksSplitAtLimit() { Add("wood", 120); Assert.AreEqual(120, s.Count("wood")); Assert.AreEqual(2, s.inventory.Count(i => i.id == "wood")); Assert.IsTrue(s.inventory.All(i => i.count <= 99)); }
        [Test] public void CapacityFailureIsAtomic() { Add("wood", 19 * 99); string before = Snapshot(); Assert.IsFalse(Rules.Transact(s, new Dictionary<string, int> { ["wood"] = -1, ["stone"] = 1 })); Assert.AreEqual(before, Snapshot()); }
        [Test] public void UnknownItemAndOverflowAreRejected() { string before = Snapshot(); Assert.IsFalse(Rules.Transact(s, new Dictionary<string, int> { ["fake"] = 1 })); Assert.IsFalse(Rules.Transact(s, new Dictionary<string, int> { ["wood"] = int.MaxValue })); Assert.AreEqual(before, Snapshot()); }
        [Test] public void CraftRequiresMaterialsAndWorkbench() { Add("wood", 2); string before = Snapshot(); Assert.IsFalse(Rules.Craft(s, "potion", true)); Assert.AreEqual(before, Snapshot()); Add("stone", 1); before = Snapshot(); Assert.IsFalse(Rules.Craft(s, "potion", false)); Assert.AreEqual(before, Snapshot()); Assert.IsTrue(Rules.Craft(s, "potion", true)); Assert.AreEqual(0, s.Count("wood")); Assert.AreEqual(3, s.Count("potion")); }
        [Test] public void CraftCanReuseFreedCapacity() { s.inventory.Clear(); Add("wood", 99 * 19); Add("stone", 1); Assert.IsTrue(Rules.Craft(s, "potion", true)); Assert.AreEqual(20, s.inventory.Count); }
        [Test] public void RewardsAreIdempotent() { var reward = new Dictionary<string, int> { ["wood"] = 5 }; Assert.IsTrue(Rules.Claim(s, "wood-0", reward)); string before = Snapshot(); Assert.IsFalse(Rules.Claim(s, "wood-0", reward)); Assert.AreEqual(before, Snapshot()); }
        [Test] public void FailedRewardIsNotMarkedClaimed() { Add("wood", 19 * 99); Assert.IsFalse(Rules.Claim(s, "stone-0", new Dictionary<string, int> { ["stone"] = 1 })); Assert.IsFalse(s.claimed.Contains("stone-0")); }
        [Test] public void CampRewardRequiresAllGuards() { var reward = new Dictionary<string, int> { ["core"] = 1 }; Assert.IsFalse(Rules.Claim(s, "camp-reward", reward)); s.defeated.AddRange(WorldCatalog.CampEnemies); Assert.IsTrue(Rules.Claim(s, "camp-reward", reward)); }
        [Test] public void UpgradeIsExactlyOnce() { Add("core", 2); Add("ore", 10); Assert.IsTrue(Rules.Upgrade(s, true)); string before = Snapshot(); Assert.IsFalse(Rules.Upgrade(s, true)); Assert.AreEqual(before, Snapshot()); Assert.AreEqual(2, s.weaponLevel); }
        [TestCase(100)] [TestCase(0)] public void HealingAtInvalidHealthDoesNotConsume(int hp) { s.hp = hp; string before = Snapshot(); Assert.IsFalse(Rules.Heal(s)); Assert.AreEqual(before, Snapshot()); }
        [Test] public void HealCapsAtMaximum() { s.hp = 80; Assert.IsTrue(Rules.Heal(s)); Assert.AreEqual(100, s.hp); Assert.AreEqual(1, s.Count("potion")); }
        [Test] public void BuildingBoundsSupportOverlapAndCollisionAreAtomic() { Add("floor", 3); Add("wall", 4); Add("roof", 1); string before = Snapshot(); Assert.IsFalse(Rules.Place(s, "floor", 0, 0, 0, true)); Assert.IsFalse(Rules.Place(s, "wall", -2, 0, 0, true)); Assert.IsFalse(Rules.Place(s, "floor", -2, 0, 0, false)); Assert.AreEqual(before, Snapshot()); Assert.IsTrue(Rules.Place(s, "floor", -2, 0, 0, true)); Assert.IsFalse(Rules.Place(s, "floor", -2, 0, 0, true)); Assert.IsFalse(Rules.Place(s, "roof", -2, 0, 0, true)); Assert.IsTrue(Rules.Place(s, "wall", -2, 0, 0, true)); Assert.IsTrue(Rules.Place(s, "wall", -2, 0, 1, true)); Assert.IsTrue(Rules.Place(s, "roof", -2, 0, 0, true)); }
        [Test] public void SharedWallCannotOverlap() { Add("floor", 2); Add("wall", 2); Rules.Place(s, "floor", -2, 0, 0, true); Rules.Place(s, "floor", -1, 0, 0, true); Assert.IsTrue(Rules.Place(s, "wall", -2, 0, 1, true)); Assert.IsFalse(Rules.Place(s, "wall", -1, 0, 3, true)); }
        [Test] public void RemovalRespectsDependenciesAndConservesModules() { Add("floor", 1); Add("wall", 1); Rules.Place(s, "floor", -2, 0, 0, true); Rules.Place(s, "wall", -2, 0, 0, true); string floor = s.buildings[0].id, wall = s.buildings[1].id; Assert.IsFalse(Rules.Remove(s, floor)); Assert.IsTrue(Rules.Remove(s, wall)); Assert.IsFalse(Rules.Remove(s, wall)); Assert.IsTrue(Rules.Remove(s, floor)); Assert.AreEqual(1, s.Count("floor")); Assert.AreEqual(1, s.Count("wall")); }
        [Test] public void FullInventoryCannotRemoveBuilding() { Add("floor", 1); Rules.Place(s, "floor", -2, 0, 0, true); Add("wood", 19 * 99); string before = Snapshot(); Assert.IsFalse(Rules.Remove(s, s.buildings[0].id)); Assert.AreEqual(before, Snapshot()); }
        [Test] public void OutOfOrderExplorationDoesNotBlockObjectives() { s.defeated.AddRange(WorldCatalog.CampEnemies); s.claimed.AddRange(new[] { "camp-reward", "wood-0", "stone-0" }); s.craftedPotion = s.placedBuilding = true; s.weaponLevel = 2; Assert.IsTrue(Rules.Objective(s).StartsWith("06")); }
        [Test] public void SaveRoundTripKeepsEverything() { Add("floor", 1); Rules.Place(s, "floor", -2, 0, 1, true); s.x = 9; s.z = 10; s.hp = 56; s.yaw = 54; s.selectedSlot = 2; s.claimed.Add("chest-forest"); s.defeated.Add("enemy-wild-0"); var store = new SaveStore(path); Assert.IsTrue(store.Save(s, out _)); Assert.IsTrue(store.Load(out var loaded, out _)); Assert.AreEqual(Snapshot(), JsonUtility.ToJson(loaded)); }
        [Test] public void CorruptPrimaryRestoresBackupAndKeepsHealthyBackupOnNextSave() { var store = new SaveStore(path); store.Save(s, out _); s.hp = 50; store.Save(s, out _); File.WriteAllText(path, "broken"); Assert.IsTrue(store.Load(out var loaded, out string message)); Assert.AreEqual(100, loaded.hp); Assert.IsTrue(message.Contains("备份")); Assert.IsTrue(store.Save(loaded, out _)); Assert.IsTrue(new SaveStore(path + ".bak").Load(out _, out _)); }
        [TestCase("{\"version\":999}")] [TestCase("{}")] [TestCase("not-json")] public void InvalidSaveIsProtectedUntilExplicitArchive(string json) { File.WriteAllText(path, json); var store = new SaveStore(path); Assert.IsFalse(store.Load(out _, out _)); Assert.IsTrue(store.Blocked); Assert.IsFalse(store.Save(s, out _)); Assert.AreEqual(json, File.ReadAllText(path)); store.Archive(); Assert.IsTrue(store.Save(s, out _)); Assert.AreEqual(1, Directory.GetFiles(folder, "*.archived-*").Length); }
        [Test] public void InterruptedTemporaryWriteDoesNotReplacePrimary() { var store = new SaveStore(path); store.Save(s, out _); File.WriteAllText(path + ".tmp", "half written"); Assert.IsTrue(store.Load(out var loaded, out _)); Assert.AreEqual(100, loaded.hp); }
        [Test] public void FutureSaveIsProtectedEvenWhenAnOldBackupExists() { var store = new SaveStore(path); store.Save(s, out _); store.Save(s, out _); File.WriteAllText(path, "{\"version\":3}"); Assert.IsFalse(store.Load(out _, out _)); Assert.IsTrue(store.Blocked); Assert.IsFalse(store.Save(s, out _)); Assert.AreEqual("{\"version\":3}", File.ReadAllText(path)); }
        [Test] public void UnknownIdsAndUnsupportedBuildingsFailValidation() { s.claimed.Add("bad-id"); Assert.IsFalse(SaveStore.Validate(s)); s.claimed.Clear(); s.buildings.Add(new BuildingState("roof", -2, 0, 0)); Assert.IsFalse(SaveStore.Validate(s)); }
        [TestCase(0, 0)] [TestCase(100, 500)] public void InvalidOrDeadPositionReturnsToCamp(int hp, float x) { s.hp = hp; s.x = x; SaveStore.SafePosition(s); Assert.AreEqual(100, s.hp); Assert.AreEqual(0, s.x); Assert.AreEqual(1, s.y); }
        [Test] public void NonFiniteCoordinatesAreRecovered() { s.z = float.NaN; SaveStore.SafePosition(s); Assert.AreEqual(0, s.z); }
        [Test] public void CompleteAdventureConservesResourcesAndSurvivesReload() { for (int i = 0; i < 6; i++) Rules.Claim(s, "wood-" + i, new Dictionary<string, int> { ["wood"] = 5 }); for (int i = 0; i < 3; i++) Rules.Claim(s, "stone-" + i, new Dictionary<string, int> { ["stone"] = 4 }); Rules.Craft(s, "potion", true); foreach (string part in new[] { "floor", "wall", "wall", "roof" }) Assert.IsTrue(Rules.Craft(s, part, true)); Rules.Place(s, "floor", -2, 0, 0, true); Rules.Place(s, "wall", -2, 0, 0, true); Rules.Place(s, "wall", -2, 0, 1, true); Rules.Place(s, "roof", -2, 0, 0, true); s.defeated.AddRange(WorldCatalog.CampEnemies); Rules.Claim(s, "camp-reward", new Dictionary<string, int> { ["core"] = 1, ["ore"] = 5 }); Assert.IsTrue(Rules.Upgrade(s, true)); Assert.IsTrue(Rules.Objective(s).StartsWith("旅程完成")); var store = new SaveStore(path); Assert.IsTrue(store.Save(s, out _)); Assert.IsTrue(store.Load(out var loaded, out _)); Assert.AreEqual(Snapshot(), JsonUtility.ToJson(loaded)); }
    }
}
